theme: jekyll-theme-cayman
title: Dominic DiSanto
description: Included on this page is information related to the repositories containd in my GitHub profile, insights into my experience as a graduate student and analyst, and projects of my own interest to better my understanding of statistics and mathematics
